/**
 * 네이버 로그인에 필요한 파라미터 타입
 * (Parameters required for Naver login)
 */
type Props = {
  /**
   * 애플리케이션 등록 시 발급 받은 클라이언트 아이디 (Client ID issued when registering the application)
   */
  clientId: string;

  /**
   * 애플리케이션을 등록 시 입력한 Callback URL 값 (Callback URL value entered when registering the application)
   * @example 'https://example.com/callback'
   */
  redirectUri: string;

  /**
   * 사이트 간 요청 위조(cross-site request forgery) 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰값으로 URL 인코딩을 적용한 값을 사용
   * (URL-encoded state token value generated by the application to prevent cross-site request forgery attacks)
   * @example 'random-state-token-12345'
   */
  state: string;
};

/**
 * 네이버 로그인 요청 URL. (Naver login request URL.)
 */
const NAVER_LOGIN_URL = 'https://nid.naver.com/oauth2.0/authorize';

/**
 * 네이버 로그인 URL 생성. (Create Naver login URL.)
 *
 * 네이버 OAuth 2.0 인증을 위한 URL을 생성합니다.
 * (Generates a URL for Naver OAuth 2.0 authentication.)
 *
 * @param props - 네이버 로그인에 필요한 파라미터
 * @returns 네이버 로그인 페이지 URL ('https://nid.naver.com/oauth2.0/authorize?client_id=...')
 *
 * @example
 * ```typescript
 * const url = makeNaverLoginUrl({
 *   clientId: 'YOUR_CLIENT_ID',
 *   redirectUri: 'https://example.com/callback',
 *   state: 'random-state-token'
 * });
 * ```
 */
export const makeNaverLoginUrl = ({ clientId, redirectUri, state }: Props) => {
  const params = new URLSearchParams();

  params.append('client_id', clientId);
  params.append('redirect_uri', redirectUri);
  params.append('response_type', 'code');
  params.append('state', state);

  return `${NAVER_LOGIN_URL}?${params.toString()}`;
};

/**
 * 네이버 로그인 리다이렉트. (Naver login redirect.)
 *
 * 브라우저를 네이버 로그인 페이지로 리다이렉트합니다.
 * (Redirects the browser to the Naver login page.)
 *
 * @param props - 네이버 로그인에 필요한 파라미터
 *
 * @example
 * ```typescript
 * naverLogin({
 *   clientId: 'YOUR_CLIENT_ID',
 *   redirectUri: 'https://example.com/callback',
 *   state: 'random-state-token'
 * });
 * ```
 */
export const naverLogin = ({ clientId, redirectUri, state }: Props) => {
  // Generate Naver login URL.
  const url = makeNaverLoginUrl({ clientId, redirectUri, state });

  // Redirect to Naver login page.
  window.location.href = url;
};
