import { strict as assert } from "node:assert";
import { test } from "node:test";

import {
  makeLineLoginUrl,
  makeNaverLoginUrl,
} from "../dist/index.js";

test("builds a LINE authorization URL from required and optional inputs", () => {
  /** LINE callback URL containing a query parameter. */
  const redirectUri = "https://example.com/auth/line/callback?source=web";
  /** LINE authorization URL generated by the public helper. */
  const url = new URL(
    makeLineLoginUrl({
      client_id: "client-id",
      redirect_uri: redirectUri,
      state: "state-value",
      scope: "profile openid email",
      nonce: "nonce-value",
      prompt: "consent",
      max_age: 0,
      ui_locales: "ko-KR en-US",
      bot_prompt: "normal",
      initial_amr_display: "lineqr",
      switch_amr: false,
      disable_auto_login: true,
      disable_ios_auto_login: false,
      code_challenge: "challenge-value",
      code_challenge_method: "S256",
      response_mode: "query.jwt",
    }),
  );

  assert.equal(url.origin, "https://access.line.me");
  assert.equal(url.pathname, "/oauth2/v2.1/authorize");
  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("state"), "state-value");
  assert.equal(url.searchParams.get("scope"), "profile openid email");
  assert.equal(url.searchParams.get("max_age"), "0");
  assert.equal(url.searchParams.get("switch_amr"), "false");
  assert.equal(url.searchParams.get("disable_ios_auto_login"), "false");
  assert.equal(url.searchParams.get("response_mode"), "query.jwt");
  assert.equal(url.searchParams.get("version"), null);
});

test("maps Naver inputs to provider query parameter names", () => {
  /** Naver callback URL used for the authorization request. */
  const redirectUri = "https://example.com/auth/naver/callback";
  /** Naver authorization URL generated by the public helper. */
  const url = new URL(
    makeNaverLoginUrl({
      clientId: "client-id",
      redirectUri,
      state: "state-value",
    }),
  );

  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("state"), "state-value");
  assert.equal(url.searchParams.get("clientId"), null);
  assert.equal(url.searchParams.get("redirectUri"), null);
});
