import { strict as assert } from "node:assert";
import { test } from "node:test";

import {
  makeGoogleLoginUrl,
  makeLineLoginUrl,
  makeNaverLoginUrl,
} from "../dist/index.js";

test("builds a Google authorization URL from public inputs", () => {
  const redirectUri =
    "https://example.com/auth/google/callback?source=web&return=%2Fdashboard";
  const url = new URL(
    makeGoogleLoginUrl({
      client_id: "client-id",
      redirect_uri: redirectUri,
      scope: "openid email profile",
      state: "state-value&attempt=1",
      access_type: "offline",
      include_granted_scopes: "true",
      enable_granular_consent: "false",
      login_hint: "user@example.com",
      prompt: "select_account",
      response_type: undefined,
    }),
  );

  assert.equal(url.origin, "https://accounts.google.com");
  assert.equal(url.pathname, "/o/oauth2/v2/auth");
  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("scope"), "openid email profile");
  assert.equal(url.searchParams.get("state"), "state-value&attempt=1");
  assert.equal(url.searchParams.get("access_type"), "offline");
  assert.equal(url.searchParams.get("include_granted_scopes"), "true");
  assert.equal(url.searchParams.get("enable_granular_consent"), "false");
  assert.equal(url.searchParams.get("login_hint"), "user@example.com");
  assert.equal(url.searchParams.get("prompt"), "select_account");
  assert.equal(url.searchParams.has("undefined"), false);
});

test("omits undefined Google optional inputs", () => {
  const url = new URL(
    makeGoogleLoginUrl({
      client_id: "client-id",
      redirect_uri: "https://example.com/auth/google/callback",
      scope: "openid email",
      state: undefined,
      access_type: undefined,
    }),
  );

  assert.equal(url.searchParams.has("state"), false);
  assert.equal(url.searchParams.has("access_type"), false);
});

test("builds a LINE authorization URL from required and optional inputs", () => {
  /** LINE callback URL containing a query parameter. */
  const redirectUri = "https://example.com/auth/line/callback?source=web";
  /** LINE authorization URL generated by the public helper. */
  const url = new URL(
    makeLineLoginUrl({
      client_id: "client-id",
      redirect_uri: redirectUri,
      state: "state-value",
      scope: "profile openid email",
      nonce: "",
      prompt: undefined,
      max_age: 0,
      ui_locales: "ko-KR en-US",
      bot_prompt: "normal",
      initial_amr_display: "lineqr",
      switch_amr: false,
      disable_auto_login: true,
      disable_ios_auto_login: false,
      code_challenge: "challenge-value",
      code_challenge_method: "S256",
      response_mode: "query.jwt",
    }),
  );

  assert.equal(url.origin, "https://access.line.me");
  assert.equal(url.pathname, "/oauth2/v2.1/authorize");
  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("state"), "state-value");
  assert.equal(url.searchParams.get("scope"), "profile openid email");
  assert.equal(url.searchParams.get("max_age"), "0");
  assert.equal(url.searchParams.get("switch_amr"), "false");
  assert.equal(url.searchParams.get("disable_ios_auto_login"), "false");
  assert.equal(url.searchParams.get("response_mode"), "query.jwt");
  assert.equal(url.searchParams.has("nonce"), true);
  assert.equal(url.searchParams.get("nonce"), "");
  assert.equal(url.searchParams.get("prompt"), null);
  assert.equal(url.searchParams.get("version"), null);
});

test("keeps a requested LINE OAuth version in the endpoint path", () => {
  /** LINE authorization URL generated for an explicitly requested version. */
  const url = new URL(
    makeLineLoginUrl({
      version: "v2.0",
      client_id: "client-id",
      redirect_uri: "https://example.com/auth/line/callback",
      state: "state-value",
      scope: "profile",
    }),
  );

  assert.equal(url.origin, "https://access.line.me");
  assert.equal(url.pathname, "/oauth2/v2.0/authorize");
  assert.equal(url.searchParams.get("version"), null);
  assert.equal(url.searchParams.get("response_type"), "code");
});

test("maps Naver inputs to provider query parameter names", () => {
  /** Naver callback URL used for the authorization request. */
  const redirectUri =
    "https://example.com/auth/naver/callback?source=web&return=%2Fdashboard";
  /** Naver authorization URL generated by the public helper. */
  const url = new URL(
    makeNaverLoginUrl({
      clientId: "client-id",
      redirectUri,
      state: "state-value&attempt=1",
    }),
  );

  assert.equal(url.origin, "https://nid.naver.com");
  assert.equal(url.pathname, "/oauth2.0/authorize");
  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("state"), "state-value&attempt=1");
  assert.equal(url.searchParams.get("clientId"), null);
  assert.equal(url.searchParams.get("redirectUri"), null);
});
