import { strict as assert } from "node:assert";
import { test } from "node:test";

import { makeNaverLoginUrl } from "../dist/index.js";

test("maps Naver inputs to provider query parameter names", () => {
  /** Naver callback URL used for the authorization request. */
  const redirectUri = "https://example.com/auth/naver/callback";
  /** Naver authorization URL generated by the public helper. */
  const url = new URL(
    makeNaverLoginUrl({
      clientId: "client-id",
      redirectUri,
      state: "state-value",
    }),
  );

  assert.equal(url.searchParams.get("response_type"), "code");
  assert.equal(url.searchParams.get("client_id"), "client-id");
  assert.equal(url.searchParams.get("redirect_uri"), redirectUri);
  assert.equal(url.searchParams.get("state"), "state-value");
  assert.equal(url.searchParams.get("clientId"), null);
  assert.equal(url.searchParams.get("redirectUri"), null);
});
